
DROP TABLE IF EXISTS playlists_tracks CASCADE;
DROP TABLE IF EXISTS tracks CASCADE;
DROP TABLE IF EXISTS playlists CASCADE;

CREATE TABLE playlists (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT NOT NULL
);

CREATE TABLE tracks (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  duration_ms INTEGER NOT NULL
);


CREATE TABLE playlists_tracks (
  id SERIAL PRIMARY KEY,
  playlist_id INT NOT NULL REFERENCES playlists (id) ON UPDATE CASCADE ON DELETE CASCADE,
  track_id INT NOT NULL REFERENCES tracks (id)     ON UPDATE CASCADE ON DELETE CASCADE,
  UNIQUE (playlist_id, track_id)
);
